### PR TITLE
Update lessons to use Blueprint SDK

### PR DESCRIPTION
**Pull request by Gusarich**
Linked with https://github.com/romanovichim/TonFunClessons_ru/pull/23

### CODE REVIEW

**Comment by romanovichim** [comment]
It looks good, in the second lesson you need to remind where 35 (throw) comes from, so that the reader does not look and immediately understands where to look

**Comment by Gusarich** [comment]
@romanovichim I'm done with translations! Can you please check?

**Comment by romanovichim** [comment]
hello, I'll look within two days, if everything is ok, I'll immediately merge

**Review by Elgayar777 — APPROVED** [review]
- [ ]

**Pull request merged**
